### ISSUE TITLE
Failed to Execute pyi_rth_win32api. Module pywintypes not found.,

### ISSUE THREAD

**Issue by Gabriel-Espinoza** [ils94/PyFlyff#3]
Hi!

First, let me thank you for this tool. I haven't tested it yet, but if it is half as good as it reads, then its gonna blow my mind.

Anyway, I have a problem launching it in Windows 11. I downloaded latest "Release" and uncompressed it. When I tried to execute "PyFlyff.exe" throws the following exception:

Any idea what how to solve this?

Trace: 
```
Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32api.py", line 32, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "pywintypes.py", line 128, in <module>
  File "pywintypes.py", line 44, in __import_pywin32_system_module__
ImportError: Module 'pywintypes' isn't in frozen sys.path ['C:\\Users\\gabes\\Downloads\\PyFlyff\\base_library.zip', 'C:\\Users\\gabes\\Downloads\\PyFlyff\\lib-dynload', 'C:\\Users\\gabes\\Downloads\\PyFlyff']
```

**Comment by ils94** [comment]
Download this .dll and put it inside the PyFlyff root folder, see if this helps.
[pythoncom38.zip](https://github.com/ils94/PyFlyff/files/10457573/pythoncom38.zip)

**Comment by Gabriel-Espinoza** [comment]
Thanks. it's running now!
