### ISSUE TITLE
Icons Folder not copied to dist/PyFlyff on compilation

### ISSUE THREAD

**Issue by TippyLion28** [ils94/PyFlyff#8]
This results in an error when trying to open any of the menus

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "PyFlyff.py", line 542, in alt_control_config
  File "tkinter\__init__.py", line 1871, in wm_iconbitmap
_tkinter.TclError: bitmap "icons/PyFlyff.ico" not defined`

By copying the icons folder to the output folder, this issue is resolved

**Comment by TippyLion28** [comment]
So why not make it so the the icons folder is automatically copied into the dist folder when running a build? Sorry not familiar with how building python applications works so maybe this is a goofy question

**Comment by ils94** [comment]
> So why not make it so the the icons folder is automatically copied into the dist folder when running a build? Sorry not familiar with how building python applications works so maybe this is a goofy question

You can do that, if I remember correctly you should add this line to your .bat file:

xcopy icons dist\PyFlyff\icons\

This should copy the contents inside icons to a folder that Windows will create named "icons" inside dist\PyFlyff\
